### ISSUE TITLE
Part 5 of the tutorial and Jupyter Notebooks

### ISSUE THREAD

**Issue by aristogato-gm** [GOMC-WSU/GOMC-MoSDeF#1]
Hi!

I was running the examples of the tutorial; however, Part 5 doesn’t run. I get the following error: 

“ValueError: ERROR: There are multiple 1,4-coulombic scaling factors GOMC will only accept a singular input for the 1,4-coulombic scaling factors.”

Also I can’t run the Jupyter Notbooks, maybe I did something wrong during installation. The first thing I do was create a new enviroment, then I install jupyter, mbuild and foyer via conda. From terminal window the  .py files execute correctly (Except for part 5).  

Thank you for any help or suggestions.

**Comment by bc118** [comment]
Hello.  

Thanks for catching this.  The issue with Example 5  was the 1-4 interaction parameters for water were set for the OPLS force field not the TraPPE force field in example 5.  This was addressed here (https://github.com/GOMC-WSU/GOMC-MoSDeF/pull/3).   Once this PR is approved, likely today, it should be available via the standard cloning process. 

As far as the jupyter notebook file not running, are you calling the correct python/conda environment when you are using these notebooks? Do you have a specific error?  If you are using conda, one way to ensure that is enabled is by running the following in a terminal window:
- conda activate "your_mosdef_environment"  (activates  the conda environment)
- juypter notebook (starts the notebook with the environment above)

Otherwise, I can give you a link for a video chat and try and help resolve the issue.  Just let me know.

**Comment by aristogato-gm** [comment]
Thanks for your answer.

I will clone the repo again.

The jupyter notebooks are working  (with some warnings) after I rebooted of my computer. Now I have the files for the GOMC simulations.

I have another question, how can I create a xml file for other water model? Can I use GOMC-MoSDeF with models with virtual sites like TIP4P or TIP4P/$\epsilon$

**Comment by bc118** [comment]
Hey.  

Note that the PR is not merged yet, so you will need to clone this branch to get the changes (https://github.com/bc118/GOMC-MoSDeF/tree/spce_1_4_fix).

**Comment by bc118** [comment]
An example number 7 for the TIP4P-2005 was added to the PR above.  

As a general note, in the common folder, the .XML files are the force fields.  All the 1-4 electrostatic interactions in all the XML files must be the same (i.e., NonbondedForce coulomb14scale="0.5") or it will not let you use that combination of force fields.  This due to GOMC only allowing 1 input for the 1-4 electrostatic interactions, and also prevents bad force field mixing.  If you know that the 1-4 interactions don't matter (i.e., for water), then you can put in whatever value the other force field is using.

**Comment by aristogato-gm** [comment]
Ok, I have cloned the branch you indicate. I would like to load the molecule through mol2 file to run the examples without any modification just to be sure I built the files correctly,  but tip4p_2005.mol2 file is not in common directory. 

Thank you for the note, I will pay special attention in the 1-4 electrostatic interaction. For now I am interested in aqueous solutions.

**Comment by bc118** [comment]
The branch fix_spce_1_4 of https://github.com/bc118/GOMC-MoSDeF/tree/fix_spce_1_4 must be cloned like this

git clone https://github.com/bc118/GOMC-MoSDeF —branch fix_spce_1_4

**Comment by aristogato-gm** [comment]
Thank you very much. I will be working these days with binary mixtures in GE ensamble. I appreciate your kind reply

**Comment by aristogato-gm** [comment]
Thank you very much. I will be working these days with binary mixtures in GE ensemble. I appreciate your kind reply

**Comment by bc118** [comment]
Thanks for pointing out the issue with the Example.  

If you have any other feedback, good or bad,  please let me know, as we want to improve and add to them in the near future.  Did you like the python, jupyter notebook Examples, YouTube videos?  Were they hard or easy to understand?  Better or worse than others?  Suggested improvements? Any other comments as well.  If you don't have any comments, that's fine too. 

If comments are provided, can you please state what level of user you are, like novice, intermediate, or expert in molecular simulation.   If you want to provide them off of the Github site I can provide an email as well.

**Comment by aristogato-gm** [comment]
The tutorial help me to understand how MOSDEF can be used to build the files for a GOMC simulation. 

I suggest adding a section to show the installation of necessary packages for running the complete tutorial. Although there is a lot of information on the internet, maybe this tutorial should be self-contained. 

I realized that angles and bonds are fixed for water models; however, bonds are not fixed for other molecules.

Do you know if there is an XML file with the complete TraPPE-UA force field? In trappe-ua.xml are not all the atom types of this forcefield.  For now, I wrote some XML for particular molecules. 

I think I am an intermediate user.

**Comment by bc118** [comment]
Thanks for your feedback, as it is very much appreciated.  

The fixed bonds and angles are force field specific.  However, to my knowledge, most or all Monte Carlo simulation engines fix (do not sample) the bonds, regardless of the utilized force field.  Therefore, you should be familiar with the force field you are using.  Note: in molecular dynamics (MD) you likely need to use fixed bonds for hydrogens if your time step is 2 fs.  We are currently working on a plan to try to include fixed bonds and other items like this in the MoSDeF force field xml files, and auto-add them when possible in the MoSDeF file writers. 

The Trappe-ua force field included with foyer (MoSDeF) will not always work on every system since they are limited to the availability of parameters and the in-depth testing required to ensure they are working properly.  The same applies for the oplsaa force field.  They both should cover a wide range of systems.  There are a lot more TraPPE parameters here (http://trappe.oit.umn.edu/)  and a lot have force field xml files that work with MoSDeF.  Depending on what exactly your doing or if you want specific force field parameters, you may need to create and xml file.

**Comment by jpotoff** [comment]
I put together a video for new students in my lab that discusses the installation of all of the packages.  You can see it here: https://www.youtube.com/watch?v=C_DWz9hVQRk&list=PLdxD0z6HRx8Z3wRuj-lMVKCE2T-dvj1fm
